# Generated by Django 5.2.3 on 2025-11-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('preacher', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('audio_file', models.FileField(upload_to='sermons/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='sermons/video/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
