# Generated by Django 5.2.3 on 2025-11-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='sermons/audio/'),
        ),
    ]
